name: Incubator

on:
  workflow_dispatch:

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - id: keygen
      name: generate key
      run: | 
        ssh-keygen -b 2048 -t rsa -f ./mysshkey -q -N ""
