name: Platform Integration Tests

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - id: checkout-repo
      name: Checkout repo
      uses: actions/checkout@v2
    - id: run-integration-tests
      name: Run integration tests
      run: | 
        python3 src/main/python/it.py http://t2.stackable.tech
    - id: archive-report
      name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: output/report*.adoc
