name: Platform Integration Tests

on:
  schedule:
    - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - id: checkout-repo
      name: Checkout repo
      uses: actions/checkout@v2
    - id: run-integration-tests
      name: Run integration tests
      env:
        T2_TOKEN: ${{ secrets.T2_TOKEN }}
      run: | 
        python3 src/main/python/it.py https://t2.stackable.tech "$T2_TOKEN"
    - id: archive-report
      name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: output/report*.adoc
