name: Platform Integration Tests

on:
  schedule:
    - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - id: checkout-repo
      name: Checkout repo
      uses: actions/checkout@v2
    - id: generate-ssh-key
      name: Generate SSH key to access cluster
      run: | 
        ssh-keygen -b 2048 -t rsa -f ./mysshkey -q -N ""
    # - id: launch-cluster
    #   name: Launch cluster via T2 API
    #   env:
    #     T2_TOKEN: ${{ secrets.T2_TOKEN }}
    #   run: | 
    #     python3 src/main/python/launch.py https://t2.stackable.tech "$T2_TOKEN" mysshkey.pub
    - id: print-cluster-information
      name: Print out information about cluster
        # echo "UUID:"
        # cat cluster_uuid
        # echo
        # echo "IP:"
        # cat cluster_ip
        # echo
        # cat mysshkey.pub
        # echo
      run: | 
        ls -la
    # - id: test-ssh-connect
    #   name: Test SSH connect to cluster
    #   run: | 
    #     ssh -o "StrictHostKeyChecking no" -i mysshkey -q root@`cat cluster_ip` exit
    # - id: terminate-cluster
    #   name: Terminate cluster via T2 API
    #   env:
    #     T2_TOKEN: ${{ secrets.T2_TOKEN }}
    #   run: | 
    #     python3 src/main/python/terminate.py https://t2.stackable.tech "$T2_TOKEN" `cat cluster_uuid`
    # - id: archive-report
    #   name: Archive test report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-report
    #     path: output/report*.adoc
