name: Platform Integration Tests

on:
  schedule:
    - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - id: checkout-repo
      name: Checkout repo
      uses: actions/checkout@v2
    - id: generate-ssh-key
      name: Generate SSH key to access cluster
      run: | 
        ssh-keygen -b 2048 -t rsa -f ./mysshkey -q -N ""
    - id: launch-cluster
      name: Launch cluster via T2 API
      env:
        T2_TOKEN: ${{ secrets.T2_TOKEN }}
      run: | 
        python3 src/main/python/it.py https://t2.stackable.tech "$T2_TOKEN"
    - id: print-cluster-information
      name: Print out information about cluster
      run: | 
        echo "UUID:"
        cat cluster_uuid
        echo
        echo "IP:"
        cat cluster_ip
        echo
        cat mysshkey.pub
        echo
    # - id: archive-report
    #   name: Archive test report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-report
    #     path: output/report*.adoc
