name: Platform Integration Tests

on:
  workflow_dispatch:

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - id: checkout-repo
      name: Checkout repo
      uses: actions/checkout@v2
    - id: run-integration-tests
      name: Run integration tests
      run: | 
        cd src/main/python
        python3 it.py http://t2.stackable.tech
